spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog_platform_test
    username: test_user
    password: test_pass

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      expiration: 600000
